# Generated by Django 6.0.6 on 2026-06-16 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Disponivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('autor', models.CharField(max_length=100, verbose_name='Autor')),
                ('ano_lancamento', models.DateField(auto_now_add=True, null=True, verbose_name='Ano de lançamento')),
                ('sinopse', models.TextField(blank=True, null=True, verbose_name='Sinopse')),
                ('data_retirada', models.DateTimeField(auto_now_add=True, verbose_name='Data da retirada')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livros.categoria')),
            ],
        ),
    ]
